# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Usabit
email: contato@usabit.com.br
description: > # this means to ignore newlines until "baseurl:"
  Somos um time de desenvolvimento digital unido, integrado e aberto para o mundo.
  Criamos produtos digitais simples e fáceis de usar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://usabit.com.br" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  usabit

# Footer Information
address_line1: Av. Pastor Martin Lutherking Junior, 126
address_line2: Shopping Nova América
city: Rio de Janeiro
country: Brasil
google_map: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d759.2838215234633!2d-43.27029330841114!3d-22.87935686808418!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xf31c91cd0302bb07!2sShopping+Nova+Am%C3%A9rica!5e0!3m2!1spt-BR!2sbr!4v1478018926639

# Build settings
markdown: kramdown

gems: ['kramdown']

exclude: [
  'config.ru',
  'Gemfile',
  'Gemfile.lock',
  'Procfile',
  'Rakefile',
  'vendor',
  'node_modules',
  'gulpfile.js',
  'package.json',
  '_sass',
  '.sass-cache',
  'bower.json',
  'bower_components'
]

cases: [
  {
    id: 'aliga',
    title: 'A Liga',
    slogan: 'Todo jogo vale',
    linkhref: 'appaliga.com.br',
    linkclass: 'fa-link',
    deviceclass: 'left bottom'
  },
  {
    id: 'rxbandeirantes',
    title: 'RX Bandeirantes',
    slogan: 'Clínica Radiológica',
    linkhref: 'rxbandeirantes.com.br',
    linkclass: 'fa-link',
    deviceclass: 'right'
  },
  {
    id: 'eurovip',
    title: 'EuroVip',
    slogan: 'Transporte e Turismo',
    linkhref: 'euroviptransportes.com.br',
    linkclass: 'fa-link',
    deviceclass: 'left'
  },
  {
    id: 'matanativa',
    title: 'Mata Nativa',
    slogan: 'Pousada',
    linkhref: 'pousadamatanativa.tur.br',
    linkclass: 'fa-link',
    deviceclass: 'right'
  },
  {
    id: 'paula-moraes',
    title: 'Dra. Paula Moraes',
    slogan: 'Dentista',
    linkhref: null, #'paulamoraes.com.br',
    linkclass: 'fa-link',
    deviceclass: 'left'
  },
  {
    id: 'sanes',
    title: 'Sanes',
    slogan: 'Indústria alimentícia',
    linkhref: 'sanesbr.com.br',
    linkclass: 'fa-link',
    deviceclass: 'right'
  },
  {
    id: 'techhealthy',
    title: 'TechHealthy',
    slogan: 'Agência virtual',
    linkhref: null, #'techhealthy.com.br',
    linkclass: 'fa-link',
    deviceclass: 'left'
  }
]

social-links: [
  {
    fontawesome_icon: 'fa-facebook',
    link: 'http://fb.com/usabitdigital',
    description: '/usabitdigital'
  },
  {
    fontawesome_icon: 'fa-instagram',
    link: 'https://www.instagram.com/usabit_/',
    description: '@usabit_'
  },
  {
    fontawesome_icon: 'fa-linkedin',
    link: 'https://www.linkedin.com/company/usabit',
    description: '/company/usabit'
  }
]
