# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Usabit Digital
email: contato@usabit.com.br
description: > # this means to ignore newlines until "baseurl:"
  Somos um time de desenvolvimento digital unido, integrado e aberto para o mundo.
  Criamos produtos digitais simples e fáceis de usar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://usabit.com.br" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  usabit

# Build settings
markdown: kramdown

exclude: [
  'node_modules', 
  '.gulpfile.js',
  'package.json',
  '_sass',
  '.sass-cache',
  'bower.json'
]
